import Link from 'next/link';
import { ReactNode } from 'react';

interface ArticleLayoutProps {
  part: string;       // "PART ONE", "PART TWO" etc.
  title: string;      // article title
  children: ReactNode;
}

export default function ArticleLayout({ part, title, children }: ArticleLayoutProps) {
  return (
    <main style={{
      minHeight: '100vh',
      background: '#0A3D1F',
      color: '#F5F0E8',
      fontFamily: '"DM Sans", -apple-system, BlinkMacSystemFont, sans-serif',
    }}>
      <div style={{
        maxWidth: 720,
        margin: '0 auto',
        padding: '64px 24px 96px',
      }}>
        {/* Breadcrumb back to series */}
        <div style={{ marginBottom: 48 }}>
          <Link href="/method" style={{
            fontFamily: '"DM Mono", monospace',
            fontSize: 11,
            letterSpacing: '0.12em',
            textTransform: 'uppercase',
            color: '#C9A84C',
            textDecoration: 'none',
          }}>
            ← The Method
          </Link>
        </div>

        {/* Series + part label */}
        <div style={{
          fontFamily: '"DM Mono", monospace',
          fontSize: 11,
          letterSpacing: '0.16em',
          textTransform: 'uppercase',
          color: '#C9A84C',
          marginBottom: 20,
        }}>
          How PaceMap Reads a Race · {part}
        </div>

        {/* Title — Bebas Neue per brand book */}
        <h1 style={{
          fontFamily: '"Bebas Neue", "Arial Black", Impact, sans-serif',
          fontSize: 'clamp(48px, 8vw, 72px)',
          fontWeight: 400,
          lineHeight: 1.0,
          margin: '0 0 56px',
          letterSpacing: '0.01em',
          textTransform: 'uppercase',
          color: '#F5F0E8',
        }}>
          {title}
        </h1>

        {/* Body */}
        <div className="article-body">
          {children}
        </div>

        {/* Footer transparency note */}
        <div style={{
          marginTop: 96,
          paddingTop: 28,
          borderTop: '1px solid rgba(201, 168, 76, 0.25)',
          fontFamily: '"DM Mono", monospace',
          fontSize: 11,
          letterSpacing: '0.04em',
          lineHeight: 1.7,
          color: 'rgba(245, 240, 232, 0.7)',
        }}>
          PaceMap publishes race shape analysis for British and Irish racing.
          The analysis is generated by the ANCHOR engine and written up
          automatically from its output. PaceMap does not publish tips.
        </div>
      </div>

      <style>{`
        .article-body {
          font-family: "DM Sans", -apple-system, BlinkMacSystemFont, sans-serif;
          font-size: 17px;
          line-height: 1.75;
          color: #F5F0E8;
          font-weight: 400;
        }
        .article-body p {
          margin: 0 0 1.5em;
        }
        .article-body p:last-child {
          margin-bottom: 0;
        }
        .article-body h2 {
          font-family: "Bebas Neue", "Arial Black", Impact, sans-serif;
          font-size: clamp(26px, 4vw, 32px);
          font-weight: 400;
          line-height: 1.05;
          margin: 2.6em 0 0.9em;
          color: #F5F0E8;
          letter-spacing: 0.02em;
          text-transform: uppercase;
        }
        .article-body h2:first-child {
          margin-top: 0;
        }
        .article-body strong {
          font-weight: 600;
          color: #F5F0E8;
        }
        .article-body em {
          font-style: italic;
          color: #F5F0E8;
        }
        .article-body a {
          color: #C9A84C;
          text-decoration: underline;
          text-underline-offset: 3px;
        }
        .article-body a:hover {
          color: #E8CC7A;
        }
        .article-body hr {
          border: 0;
          border-top: 1px solid rgba(201, 168, 76, 0.3);
          margin: 3.2em 0;
        }

        /* Findings table — DM Mono for the data feel */
        .findings-heading {
          font-family: "DM Mono", monospace;
          font-size: 11px;
          letter-spacing: 0.16em;
          text-transform: uppercase;
          color: #C9A84C;
          margin: 0 0 18px;
          font-weight: 400;
        }
        .article-body table {
          width: 100%;
          border-collapse: collapse;
          margin: 1.2em 0;
          font-family: "DM Mono", monospace;
          font-size: 13px;
          background: #1A5C32;
        }
        .article-body th, .article-body td {
          padding: 14px 16px;
          text-align: left;
          border-bottom: 1px solid rgba(245, 240, 232, 0.1);
        }
        .article-body th {
          font-family: "DM Mono", monospace;
          font-size: 10px;
          font-weight: 400;
          letter-spacing: 0.12em;
          text-transform: uppercase;
          color: #C9A84C;
          background: #0A3D1F;
          border-bottom: 1px solid rgba(201, 168, 76, 0.3);
        }
        .article-body td {
          color: #F5F0E8;
        }
        .article-body td:nth-child(2),
        .article-body td:nth-child(3),
        .article-body td:nth-child(4) {
          color: #E8CC7A;
        }
        .article-body tr:last-child td {
          border-bottom: none;
        }
        .article-body .findings-caption {
          font-family: "DM Sans", sans-serif;
          font-size: 13px;
          font-style: italic;
          color: rgba(245, 240, 232, 0.65);
          line-height: 1.6;
          margin-top: 14px;
        }
      `}</style>
    </main>
  );
}
