// AUTO-GENERATED by PaceMap daily generator
// Meeting: Warwick — 26 March 2026
// Do not edit manually

"use client";

import Nav from "@/components/Nav";
import Link from "next/link";
import { useUser } from "@clerk/nextjs";
import { useEffect, useState } from "react";

const MEETING_META = {
  course: "Warwick",
  date:   "26 March 2026",
  slug:   "warwick-26-march-2026",
};

const RACES = [
  {
    "id": 1,
    "time": "2:28",
    "name": "Feldon Dunsmore Proudly Employee-Owned Novices' Hurdle (GBB Race)",
    "grade": "NOV",
    "dist": "2m5f",
    "dist_f": 21.0,
    "going": "Good",
    "free": true,
    "type": "jumps",
    "pace": "SLOWLY_RUN",
    "paceConf": 85,
    "leads": [],
    "prominent": [],
    "midfield": [],
    "holdup": [],
    "drawBias": null,
    "runners_data": [
      {
        "name": "Bobbarelli",
        "or": 105,
        "projected": 103.0,
        "model_price": "6/4",
        "mkt_price": "n/a",
        "win_pct": 39.2,
        "edge": 14.2,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Big Ticket",
        "or": 125,
        "projected": 119.1,
        "model_price": "6/4",
        "mkt_price": "n/a",
        "win_pct": 36.6,
        "edge": 10.2,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "La Vish",
        "or": 100,
        "projected": 59.5,
        "model_price": "3/1",
        "mkt_price": "n/a",
        "win_pct": 24.2,
        "edge": -24.4,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      }
    ],
    "narrative": "## RACE SHAPE\nWith only three runners in this slowly-run novice hurdle, expect a tactical affair over 2m5f at Warwick. Big Ticket, as the highest-rated runner (OR 125), will likely be allowed an easy lead or prominent position given the small field size. The lack of natural pace setters in this grade suggests they'll crawl early before quickening from the second-last hurdle.\n\n## MOST LIKELY WINNER\nBobbarelli heads the model despite carrying the lowest official rating (OR 105), with the algorithm projecting significant improvement to 103.0. The edge appears to come from the slowly-run pace scenario suiting a hold-up performer who can outstay rivals in the closing stages. The model shows 39.2% win probability at 6/4, suggesting strong value in current conditions.\n\n## KEY DANGERS\nBig Ticket brings the highest class with OR 125 but is projected to run below that mark at 119.1, though still represents the main form threat. La Vish appears outclassed on ratings (OR 100, projected 59.5) and would need both rivals to underperform significantly, making this effectively a two-horse race.\n\n## VALUE ASSESSMENT\nThe model identifies no formal selections with all confidence levels marked as LOW, reflecting the small sample size and novice grade uncertainty. Bobbarelli shows the strongest edge at +14.2, while Big Ticket offers moderate value at +10.2, but La Vish appears overpriced with a -24.4 edge.\n\n## VERDICT\nThis looks a tactical two-horse battle between Bobbarelli and Big Ticket, with the former offering slight model preference despite inferior official ratings. However, with LOW confidence across all runners and no formal model fancies, this represents more of a watching brief than a betting opportunity in what could be an unreliable novice contest.",
    "runners": 3
  },
  {
    "id": 2,
    "time": "2:58",
    "name": "JCB Mini-Excavator Novices' Limited Handicap Hurdle",
    "grade": "HCAP",
    "dist": "3m2f",
    "dist_f": 26.0,
    "going": "Good",
    "free": false,
    "type": "jumps",
    "pace": "SLOWLY_RUN",
    "paceConf": 85,
    "leads": [],
    "prominent": [],
    "midfield": [],
    "holdup": [],
    "drawBias": null,
    "runners_data": [
      {
        "name": "Junior Des Mottes",
        "or": 86,
        "projected": 61.1,
        "model_price": "7/2",
        "mkt_price": "n/a",
        "win_pct": 22.4,
        "edge": 24.9,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Getaway Sam",
        "or": 73,
        "projected": 40.9,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 15.3,
        "edge": 17.7,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Miss Jaffa Cake",
        "or": 71,
        "projected": 38.8,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 15.3,
        "edge": 17.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Ffree Pedro",
        "or": 76,
        "projected": 37.5,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 13.6,
        "edge": 11.3,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Hitthekettle",
        "or": 70,
        "projected": 15.9,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 10.3,
        "edge": -4.3,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Silver Gale",
        "or": 78,
        "projected": 11.7,
        "model_price": "10/1",
        "mkt_price": "n/a",
        "win_pct": 9.4,
        "edge": -16.5,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Kampari",
        "or": 76,
        "projected": 2.3,
        "model_price": "13/1",
        "mkt_price": "n/a",
        "win_pct": 6.9,
        "edge": -23.9,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "El Arco",
        "or": 77,
        "projected": 0.4,
        "model_price": "14/1",
        "mkt_price": "n/a",
        "win_pct": 6.6,
        "edge": -26.8,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      }
    ],
    "narrative": "## RACE SHAPE\nWith 85% confidence in a slowly-run scenario over 3m2f, this looks set for a tactical affair with minimal early pace. The field average OR of 76 suggests modest ability levels, likely creating hesitant early fractions. Expect positioning to matter less than stamina and finishing kick in the final half-mile.\n\n## MOST LIKELY WINNER\nJunior Des Mottes leads on ability with an OR of 86 - significantly higher than the field average. The model projects 61.1 compared to nearest rival's 40.9, indicating clear class advantage over this moderate handicap field. His 22.4% win probability reflects both ratings superiority and likely suitability for the expected slow pace.\n\n## KEY DANGERS\nGetaway Sam (OR 73) sits second on projections at 40.9 and could benefit if the pace collapses completely, though needs others to underperform. Miss Jaffa Cake (OR 71, proj 38.8) represents similar value at 6/1 but requires significant improvement to bridge the class gap to the favorite.\n\n## VALUE ASSESSMENT\nThe model identifies no formal selections or fancies, suggesting limited value opportunities. While Junior Des Mottes shows clear ability advantage, the 24.9% edge appears already recognized by the market. The next three runners cluster around 6/1 with modest edges, indicating a competitive but uninspiring betting heat.\n\n## VERDICT\nJunior Des Mottes holds a clear class edge over a moderate field in what should develop into a slowly-run tactical battle. However, with no model fancies identified and edges likely absorbed by market efficiency, this appears a race to observe rather than invest in, despite the favorite's obvious credentials.",
    "runners": 8
  },
  {
    "id": 3,
    "time": "3:28",
    "name": "Best Odds Guaranteed At Betano Novices' Handicap Chase",
    "grade": "HCAP",
    "dist": "2m4f",
    "dist_f": 20.0,
    "going": "Good",
    "free": false,
    "type": "jumps",
    "pace": "CONTESTED",
    "paceConf": 50,
    "leads": [],
    "prominent": [],
    "midfield": [],
    "holdup": [],
    "drawBias": null,
    "runners_data": [
      {
        "name": "El Rojo Grande",
        "or": 88,
        "projected": 73.8,
        "model_price": "5/1",
        "mkt_price": "n/a",
        "win_pct": 16.7,
        "edge": 18.2,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Sawpit Samantha",
        "or": 71,
        "projected": 51.0,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 14.2,
        "edge": 12.4,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Kap De Triomphe",
        "or": 84,
        "projected": 60.4,
        "model_price": "7/1",
        "mkt_price": "n/a",
        "win_pct": 12.9,
        "edge": 8.8,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Kingoftheswingerz",
        "or": 97,
        "projected": 70.9,
        "model_price": "7/1",
        "mkt_price": "n/a",
        "win_pct": 12.1,
        "edge": 6.2,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Drumheller",
        "or": 87,
        "projected": 55.2,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 10.5,
        "edge": 0.5,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Claim Du Brizais",
        "or": 96,
        "projected": 62.2,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 10.0,
        "edge": -1.5,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Full Force Gale",
        "or": 95,
        "projected": 47.8,
        "model_price": "10/1",
        "mkt_price": "n/a",
        "win_pct": 8.7,
        "edge": -14.9,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Harthill",
        "or": 78,
        "projected": 31.2,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.5,
        "edge": -14.5,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Knightsbridge",
        "or": 87,
        "projected": 39.3,
        "model_price": "13/1",
        "mkt_price": "n/a",
        "win_pct": 7.4,
        "edge": -15.3,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      }
    ],
    "narrative": "## RACE SHAPE\nThe contested pace scenario suggests multiple horses will press forward early in this moderate-grade handicap chase. With no standout early leader apparent from the data, expect a searching gallop over the 2m4f trip. The good going should allow the pace to be strong throughout, potentially setting up the race for horses that can settle and stay.\n\n## MOST LIKELY WINNER\nEl Rojo Grande leads the model projections with an 18.2 edge, suggesting the market has significantly underestimated this runner. The OR of 88 sits just above field average (87), but the projected rating of 73.8 indicates strong recent form that ratings haven't fully captured. At 5/1 model price, this represents clear statistical value in a competitive field.\n\n## KEY DANGERS\nSawpit Samantha offers the biggest threat despite a modest OR of 71, with the model seeing 12.4 points of edge suggesting significant improvement potential. Kap De Triomphe (OR 84) provides solid each-way claims with consistent projections, while Kingoftherswingerz brings the highest official rating (OR 97) but may be vulnerable off top weight.\n\n## VALUE ASSESSMENT\nThe model identifies no formal selections, reflecting the competitive nature of this handicap where margins are tight. El Rojo Grande and Sawpit Samantha show the clearest statistical edges, but medium confidence ratings suggest form questions remain. The bottom three runners show significant negative edges, indicating the market has these correctly positioned.\n\n## VERDICT\nThis appears a typically competitive novice handicap chase where the model's top two preferences offer marginal value but lack compelling reasons for strong support. El Rojo Grande heads the calculations but without market prices available, no formal betting recommendation emerges from what looks a race to watch rather than play.",
    "runners": 9
  },
  {
    "id": 4,
    "time": "3:58",
    "name": "Betano Boosted Odds Every UK Race Mares' Handicap Hurdle",
    "grade": "HCAP",
    "dist": "2m",
    "dist_f": 16.0,
    "going": "Good",
    "free": false,
    "type": "jumps",
    "pace": "SLOWLY_RUN",
    "paceConf": 85,
    "leads": [],
    "prominent": [],
    "midfield": [],
    "holdup": [],
    "drawBias": null,
    "runners_data": [
      {
        "name": "Ip Up",
        "or": 112,
        "projected": 91.6,
        "model_price": "9/2",
        "mkt_price": "n/a",
        "win_pct": 18.2,
        "edge": 12.8,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Aj's Diamond",
        "or": 102,
        "projected": 79.3,
        "model_price": "5/1",
        "mkt_price": "n/a",
        "win_pct": 17.1,
        "edge": 10.5,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Chatty Girl",
        "or": 102,
        "projected": 79.0,
        "model_price": "5/1",
        "mkt_price": "n/a",
        "win_pct": 16.9,
        "edge": 10.2,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Lady Magic",
        "or": 111,
        "projected": 92.6,
        "model_price": "5/1",
        "mkt_price": "n/a",
        "win_pct": 16.6,
        "edge": 14.8,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Gower Spirit",
        "or": 97,
        "projected": 65.3,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 13.5,
        "edge": 1.5,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Pure Seduction",
        "or": 106,
        "projected": 48.5,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 10.1,
        "edge": -24.2,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Mistral Milly",
        "or": 103,
        "projected": 44.2,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.7,
        "edge": -25.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      }
    ],
    "narrative": "## RACE SHAPE\nWith 85% confidence this will be SLOWLY RUN over 2m at Warwick on good ground. In a small 7-runner mares' handicap, expect a tactical affair with modest early pace allowing the field to stay bunched. The tempo should suit horses with turn of foot rather than pure stamina.\n\n## MOST LIKELY WINNER\nIp Up (112 OR) heads the model despite being off a career-high mark, projecting at 91.6 with 18.2% win chance. The 12.8 edge suggests the ratings underestimate recent improvement or the mare handles these conditions particularly well. Her class advantage in this field should tell in a slowly-run race.\n\n## KEY DANGERS\nAj's Diamond and Chatty Girl are virtually inseparable on model ratings (17.1% vs 16.9% win chance), both projecting around 79. Lady Magic presents the puzzle - second-highest OR at 111 but model confidence is LOW despite showing 14.8 edge, suggesting inconsistency issues.\n\n## VALUE ASSESSMENT\nNo formal selections identified with market odds unavailable, but the model shows clear clustering. Top three all show double-digit edges (12.8, 10.5, 10.2) while bottom two show significant negative edges (-24.2, -25.6), creating a clear divide in this small field.\n\n## VERDICT\nIp Up appears the logical favorite with superior ratings and strong model backing in what should be a tactical contest. However, with no market prices available and relatively tight win percentages among the top four, this looks a competitive handicap where small-field dynamics could prove crucial.",
    "runners": 7
  },
  {
    "id": 5,
    "time": "4:30",
    "name": "JCB Handicap Chase (Challenger Staying Chase Series Final) (GBB Race)",
    "grade": "HCAP",
    "dist": "3m",
    "dist_f": 24.0,
    "going": "Good",
    "free": false,
    "type": "jumps",
    "pace": "SLOWLY_RUN",
    "paceConf": 85,
    "leads": [],
    "prominent": [],
    "midfield": [],
    "holdup": [],
    "drawBias": null,
    "runners_data": [
      {
        "name": "Lord Accord",
        "or": 126,
        "projected": 108.2,
        "model_price": "5/1",
        "mkt_price": "n/a",
        "win_pct": 15.6,
        "edge": 9.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "The Famous Five",
        "or": 118,
        "projected": 99.2,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 15.2,
        "edge": 8.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Yes Day",
        "or": 115,
        "projected": 94.2,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 14.4,
        "edge": 6.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "New Order",
        "or": 124,
        "projected": 100.9,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 13.6,
        "edge": 4.3,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Imperial Alex",
        "or": 117,
        "projected": 86.8,
        "model_price": "8/1",
        "mkt_price": "n/a",
        "win_pct": 11.4,
        "edge": -2.7,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Get Up Mush",
        "or": 110,
        "projected": 74.5,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 10.1,
        "edge": -8.1,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Pilsdon Pen",
        "or": 112,
        "projected": 76.1,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 10.0,
        "edge": -8.5,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Fever Dream",
        "or": 105,
        "projected": 67.6,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 9.7,
        "edge": -9.9,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "MEDIUM",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      }
    ],
    "narrative": "## RACE SHAPE\nThis 3-mile handicap chase will be slowly run (85% confidence), suiting those who can quicken late rather than frontrunners. With no obvious pacesetter in the field, expect a tactical affair with the field bunched turning for home. The modest pace scenario should favor horses with good finishing kicks over those needing to dominate from the front.\n\n## MOST LIKELY WINNER\nLord Accord tops the model ratings with a significant edge, projecting a performance rating of 108.2 despite carrying top weight off OR 126. The model sees 9.6 points of edge at 5/1, suggesting the handicapper has been overly harsh or recent form underrates current ability. His class advantage in this grade looks compelling.\n\n## KEY DANGERS\nThe Famous Five (OR 118, 8.6 edge points) and Yes Day (OR 115, 6.6 edge) both project strong performances relative to their ratings. The Famous Five needs the slow pace to suit his tactical style, while Yes Day requires the good going to bring out his best over this staying trip.\n\n## VALUE ASSESSMENT\nThe model identifies no formal selections, indicating while Lord Accord, The Famous Five, and Yes Day show theoretical edge, the confidence levels aren't sufficient for strong recommendations. The compact nature of the first four in the ratings (15.6% to 13.6% win probability) suggests a competitive heat where small margins separate the principals.\n\n## VERDICT\nThis looks a tactical staying chase where Lord Accord's class edge should prove decisive in a slowly-run affair, though the competitive nature of the contest and lack of formal model selections suggests caution. The absence of market prices prevents identifying clear value opportunities, making this more of a race to watch than bet.",
    "runners": 8
  },
  {
    "id": 6,
    "time": "5:00",
    "name": "JCB Tele-Handler \"Junior\" National Hunt Flat Race (GBB Race)",
    "grade": "CLS5",
    "dist": "2m",
    "dist_f": 16.0,
    "going": "Good",
    "free": false,
    "type": "jumps",
    "pace": "SLOWLY_RUN",
    "paceConf": 85,
    "leads": [],
    "prominent": [],
    "midfield": [],
    "holdup": [],
    "drawBias": null,
    "runners_data": [
      {
        "name": "Order Driven",
        "or": 65,
        "projected": 80.8,
        "model_price": "6/1",
        "mkt_price": "n/a",
        "win_pct": 13.4,
        "edge": 24.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Close To Me",
        "or": 78,
        "projected": 83.6,
        "model_price": "8/1",
        "mkt_price": "n/a",
        "win_pct": 11.0,
        "edge": 14.4,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Zotay Nzuri",
        "or": 92,
        "projected": 95.1,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 10.5,
        "edge": 11.9,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Aribidia",
        "or": 87,
        "projected": 89.2,
        "model_price": "9/1",
        "mkt_price": "n/a",
        "win_pct": 10.3,
        "edge": 11.0,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Affinitive",
        "or": 120,
        "projected": 102.6,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.8,
        "edge": -8.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Krackerjack",
        "or": 120,
        "projected": 102.6,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.8,
        "edge": -8.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Saint Argente",
        "or": 120,
        "projected": 102.6,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.8,
        "edge": -8.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Sevenkingsmustdie",
        "or": 120,
        "projected": 102.6,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.8,
        "edge": -8.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "The Honorable Norm",
        "or": 120,
        "projected": 102.6,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.8,
        "edge": -8.6,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Ivor Bear",
        "or": 111,
        "projected": 93.7,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.8,
        "edge": -8.5,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      },
      {
        "name": "Nightflyer",
        "or": 96,
        "projected": 76.5,
        "model_price": "12/1",
        "mkt_price": "n/a",
        "win_pct": 7.6,
        "edge": -10.7,
        "ev": 0.0,
        "kelly": 0.0,
        "action": "WATCH",
        "confidence": "LOW",
        "proxied": false,
        "draw": null,
        "draw_adv": null
      }
    ],
    "narrative": "## RACE SHAPE\n\nThis slowly-run National Hunt flat race will likely see a tactical affair over 2m on good ground. With no clear pace angle evident and 11 runners bunched in ability, expect a steady gallop building to a sprint finish. The lack of experienced early pace setters suggests several horses may look to lead, creating potential for a stop-start rhythm.\n\n## MOST LIKELY WINNER\n\nOrder Driven tops the model despite a modest OR of 65, indicating significant upside potential from the rating. The 24.6 edge suggests the model sees untapped ability well beyond current form figures. At 6/1 model odds, this represents the standout value play in a competitive field where ratings spread from 65-120.\n\n## KEY DANGERS\n\nClose To Me (OR 78) offers the next best value with 14.4 edge, likely benefiting from the slowly-run scenario with tactical speed. Zotay Nzuri (OR 92) and Aribidia (OR 87) both project above their official ratings and could benefit if the pace collapses into a sprint finish where class can emerge late.\n\n## VALUE ASSESSMENT\n\nThe model shows no formal selections, reflecting the competitive nature and rating spread across 11 runners. All confidence levels rate LOW, indicating significant uncertainty in form analysis. The edge calculation heavily favors the lower-rated horses, suggesting the handicapper may have been harsh on recent performances.\n\n## VERDICT\n\nThis is a trappy affair where the model's uncertainty reflects the reality of a wide-open contest. Order Driven represents the standout statistical edge at 6/1, but the LOW confidence rating suggests small stakes only. The slowly-run pace scenario could suit several runners, making this more a race to watch than bet heavily.",
    "runners": 11
  }
];

function DrawBadge({ adv }: { adv: string | null }) {
  if (!adv || adv === "NEUTRAL") return null;
  const style = adv === "FAVOURED"
    ? { background: "rgba(39,174,96,0.2)", color: "#2ecc71", border: "1px solid rgba(39,174,96,0.4)" }
    : { background: "rgba(231,76,60,0.2)",  color: "#e74c3c", border: "1px solid rgba(231,76,60,0.4)" };
  return <span style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.55rem", padding: "1px 5px", borderRadius: "2px", marginLeft: "4px", ...style }}>{adv === "FAVOURED" ? "✓ draw" : "✗ draw"}</span>;
}

function RaceMap({ race, hasAccess }: { race: any; hasAccess: boolean }) {
  const ranked = race.runners;
  const sels   = ranked.filter((r: any) => ["EW","BET","BASKET"].includes(r.action));
  const isFlat = race.type === "flat";

  if (!race.free && !hasAccess) {
    return (
      <div style={{ position: "relative", borderRadius: "10px", overflow: "hidden", marginBottom: "28px" }}>
        <div style={{ filter: "blur(5px)", pointerEvents: "none", opacity: 0.35, background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "10px", padding: "22px" }}>
          <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "1.35rem", color: "var(--gold)", marginBottom: "12px" }}>{race.time} — {race.name}</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "10px" }}>
            {["Lead","Prominent","Midfield","Hold Up"].map(l => <div key={l} style={{ height: "72px", background: "rgba(255,255,255,0.04)", borderRadius: "6px" }} />)}
          </div>
        </div>
        <div style={{ position: "absolute", inset: 0, background: "rgba(10,61,31,0.78)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "10px", textAlign: "center", padding: "28px" }}>
          <div style={{ fontSize: "1.6rem" }}>🔒</div>
          <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "1.2rem", color: "var(--gold)" }}>{race.time} — {race.name}</div>
          <p style={{ fontSize: "0.76rem", color: "rgba(245,240,232,0.5)", maxWidth: "300px", lineHeight: "1.6" }}>{race.grade} · {race.dist} · {race.runners} runners</p>
          <Link href="/pricing" className="btn btn-gold" style={{ marginTop: "6px" }}>Unlock Full Card →</Link>
        </div>
      </div>
    );
  }

  return (
    <div style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "10px", overflow: "hidden", marginBottom: "28px" }}>
      <div style={{ padding: "18px 22px", background: "rgba(201,168,76,0.07)", borderBottom: "1px solid rgba(201,168,76,0.14)", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "8px" }}>
        <div>
          <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "1.35rem", letterSpacing: "0.04em", color: "var(--gold)" }}>{race.time} — {race.name}</div>
          <div style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.62rem", color: "rgba(245,240,232,0.42)", marginTop: "3px" }}>{race.dist} · {race.going} · {race.grade} · {race.runners} runners</div>
        </div>
        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
          <span style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.6rem", padding: "3px 9px", borderRadius: "2px", background: "rgba(255,255,255,0.05)", color: "rgba(245,240,232,0.45)" }}>
            {race.pace} · {race.paceConf}% confidence
          </span>
          {race.free && <span style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.58rem", padding: "3px 8px", borderRadius: "2px", background: "rgba(39,174,96,0.18)", color: "#2ecc71", border: "1px solid rgba(39,174,96,0.35)" }}>FREE</span>}
          {isFlat && race.drawBias && (
            <span style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.58rem", padding: "3px 8px", borderRadius: "2px", background: "rgba(41,128,185,0.18)", color: "#5dade2", border: "1px solid rgba(41,128,185,0.35)" }}>
              Draw: {race.drawBias.favoured} favoured
            </span>
          )}
        </div>
      </div>

      <div style={{ padding: "22px" }}>

        {/* Pace distribution */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "10px", marginBottom: "22px" }}>
          {[
            { key: "leads",    label: "Lead",     color: "var(--lead)",     bg: "rgba(192,57,43,0.07)",  border: "rgba(192,57,43,0.3)"  },
            { key: "prominent",label: "Prominent", color: "var(--prominent)",bg: "rgba(230,126,34,0.06)", border: "rgba(230,126,34,0.3)" },
            { key: "midfield", label: "Midfield",  color: "var(--midfield)", bg: "rgba(41,128,185,0.06)", border: "rgba(41,128,185,0.3)" },
            { key: "holdup",   label: "Hold Up",   color: "var(--holdup)",   bg: "rgba(142,68,173,0.06)", border: "rgba(142,68,173,0.3)" },
          ].map(g => (
            <div key={g.key} style={{ padding: "12px", borderRadius: "6px", border: `1px solid ${g.border}`, background: g.bg, textAlign: "center" }}>
              <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "0.82rem", letterSpacing: "0.1em", color: g.color, marginBottom: "4px" }}>{g.label}</div>
              <div style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "1.9rem", color: g.color, lineHeight: 1, marginBottom: "4px" }}>{(race[g.key] || []).length}</div>
              <div style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.54rem", color: "rgba(245,240,232,0.42)", lineHeight: 1.65 }}>
                {(race[g.key] || []).slice(0,3).join(" · ")}{(race[g.key] || []).length > 3 ? ` +${(race[g.key] || []).length-3}` : ""}
              </div>
            </div>
          ))}
        </div>

        {/* Runner table */}
        <div style={{ overflowX: "auto", borderRadius: "6px", border: "1px solid rgba(255,255,255,0.07)", marginBottom: "18px" }}>
          <table className="pm-table">
            <thead>
              <tr>
                {isFlat && <th>Draw</th>}
                <th>Horse</th>
                <th>OR</th>
                <th>Model</th>
                <th>Market</th>
                <th>Win%</th>
                <th>Edge</th>
                <th>EV</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {ranked.map((r: any) => {
                const isSel = ["EW","BET","BASKET"].includes(r.action);
                const isFancy = r.confidence === "HIGH" && (r.kelly || 0) >= 0.5 && !isSel && r.action !== "AVOID";
                return (
                  <tr key={r.name} style={{ background: isSel ? "rgba(39,174,96,0.04)" : isFancy ? "rgba(201,168,76,0.04)" : "transparent" }}>
                    {isFlat && (
                      <td style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.68rem", color: "var(--gold)" }}>
                        {r.draw || "—"}
                        <DrawBadge adv={r.draw_adv} />
                      </td>
                    )}
                    <td>
                      <div style={{ fontWeight: 600, color: "var(--cream)", fontSize: "0.84rem" }}>{r.name}</div>
                      {r.proxied && <div style={{ fontSize: "0.56rem", color: "rgba(245,240,232,0.35)" }}>OR proxied</div>}
                    </td>
                    <td style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.72rem", color: "rgba(245,240,232,0.6)" }}>{r.or || "—"}</td>
                    <td style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.72rem", color: "var(--gold)" }}>{r.model_price || "n/a"}</td>
                    <td style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.72rem" }}>{r.mkt_price || "n/a"}</td>
                    <td style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.72rem" }}>{r.win_pct}%</td>
                    <td style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.72rem", color: (r.edge || 0) >= 0 ? "#2ecc71" : "#e74c3c" }}>
                      {r.edge !== null ? `${r.edge >= 0 ? "+" : ""}${r.edge}lb` : "—"}
                    </td>
                    <td style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.72rem", color: (r.ev || 0) >= 1.25 ? "#2ecc71" : "rgba(245,240,232,0.5)" }}>
                      {r.ev !== null ? `${r.ev}x` : "—"}
                    </td>
                    <td style={{ fontSize: "0.7rem", fontWeight: isSel ? 700 : 400, color: isSel ? "#2ecc71" : isFancy ? "var(--gold)" : "rgba(245,240,232,0.45)" }}>
                      {isSel ? `⭐ ${r.action}` : isFancy ? `👀 ${r.action}` : r.action}
                    </td>
                  </tr>
                );
              }))}
            </tbody>
          </table>
        </div>

        {/* Selections */}
        {sels.length > 0 && (
          <div style={{ background: "rgba(39,174,96,0.07)", border: "1px solid rgba(39,174,96,0.2)", borderRadius: "7px", padding: "14px 18px", marginBottom: "16px" }}>
            <p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "0.85rem", letterSpacing: "0.12em", color: "#2ecc71", marginBottom: "8px" }}>⭐ SELECTIONS</p>
            {sels.map((r: any) => (
              <p key={r.name} style={{ fontSize: "0.78rem", color: "var(--cream)", marginBottom: "4px" }}>
                <strong>{r.name}</strong> · {r.mkt_price} · EV {r.ev}x · JOBY {r.kelly}% · {r.action}
              </p>
            ))}
          </div>
        )}

        {/* Narrative */}
        {race.narrative && (
          <div style={{ background: "rgba(201,168,76,0.055)", border: "1px solid rgba(201,168,76,0.18)", borderRadius: "7px", padding: "16px 20px" }}>
            <p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "0.88rem", letterSpacing: "0.12em", color: "var(--gold)", marginBottom: "10px" }}>
              ⚡ Pace Analysis
            </p>
            {race.narrative.split("\n\n").map((para: string, i: number) => (
              para.startsWith("## ") ? (
                <p key={i} style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "0.82rem", letterSpacing: "0.1em", color: "var(--gold-light)", marginTop: "12px", marginBottom: "4px" }}>
                  {para.replace("## ", "")}
                </p>
              ) : (
                <p key={i} style={{ fontSize: "0.77rem", lineHeight: "1.78", color: "rgba(245,240,232,0.72)", marginBottom: "6px" }}>
                  {para}
                </p>
              )
            ))}
          </div>
        )}

      </div>
    </div>
  );
}

export default function MeetingPage() {
  const { isSignedIn } = useUser();
  const [hasAccess, setHasAccess] = useState(false);
  const [checking, setChecking] = useState(true);

  useEffect(() => {
    if (!isSignedIn) { setChecking(false); return; }
    fetch("/api/check-subscription")
      .then(r => r.json())
      .then(d => { setHasAccess(d.active); setChecking(false); })
      .catch(() => setChecking(false));
  }, [isSignedIn]);

  return (
    <>
      <Nav />
      <div className="wrap">
        <div style={{ marginBottom: "28px", paddingBottom: "18px", borderBottom: "1px solid rgba(201,168,76,0.18)", display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: "10px" }}>
          <div>
            <p style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.6rem", letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(245,240,232,0.35)", marginBottom: "6px" }}>
              <Link href="/archive" style={{ color: "rgba(245,240,232,0.35)" }}>Archive</Link>
              <span style={{ margin: "0 6px" }}>›</span>
              {MEETING_META.course} · {MEETING_META.date}
            </p>
            <h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "2rem", letterSpacing: "0.04em", color: "var(--cream)" }}>
              {MEETING_META.course}
            </h1>
            <p style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.64rem", color: "rgba(245,240,232,0.38)", marginTop: "3px" }}>
              {MEETING_META.date} · {RACES.length} races
            </p>
          </div>
          <p style={{ fontFamily: "'DM Mono',monospace", fontSize: "0.62rem", color: "rgba(245,240,232,0.3)", textAlign: "right", lineHeight: "1.7" }}>
            {checking ? "Checking access…" : hasAccess ? "✓ Full access" : "Race 1 free · Rest locked"}
          </p>
        </div>

        {RACES.map((race: any) => (
          <RaceMap key={race.id} race={race} hasAccess={hasAccess} />
        ))}
      </div>

      <footer>
        <span className="footer-brand">PaceMap</span>
        <span className="footer-note">pacemap.co.uk · A Signalweight product<br />For informational purposes only · Not financial advice</span>
      </footer>
    </>
  );
}
